Sprint 1/step 2
LarisaK12/react-burger pull request #3
Opened 2021-11-18 18:14 UTC by LarisaK12

Уважаемый ревьюер, у меня есть несколько комментариев по моей работе. Из чек-листа не выполнено требование о создании проекта через CRA с шаблоном typescript, поскольку у меня не создавался этот шаблон (помочь никто не смог) и наставник  решил, что будем делать с jsx-шаблоном. Также нет отдельного компонента ModalOverlay, но так как верстка отвечает требованиям (подложка полупрозрачная есть, на клик по ней закрывается модальное окно), то я оставила так. Не вижу смысла делать отдельный компонент, но если я ошибаюсь, то, прошу, напишите почему.

2021-11-18 19:14 UTC, grishbar commented
привет, прикрепи пожалуйста сюда скриншот ошибки, которая выходит при установки проекта при помощи CRA, также, чтобы было видно, какую команду запускаешь, по сути если запускаешь такую команду как ниже проблем быть не может
```
npx create-react-app my-app --template typescript
```

2021-11-18 20:20 UTC, LarisaK12 commented
Попробовала еще раз и получилось! Но ведь не получалось, мамой клянусь! Вот такое в логе было:
13 http fetch GET 404 https://registry.npmjs.org/cra-template-typescrypt 134ms
14 http fetch GET 404 https://registry.npmjs.org/cra-template-typescrypt 39ms
15 silly fetchPackageMetaData error for cra-template-typescrypt@latest 404 Not Found - GET https://registry.npmjs.org/cra-template-typescrypt - Not found
При этом инет был, пробовала ссылку в браузере выполнить - возвращал {"Error":"Nof found"}. Видимо просто не повезло, были проблемы на сервере. Так что мне теперь делать? Переделывать на typescript -шаблоне, или можно так зачесть?

2021-11-18 20:42 UTC, grishbar requested changes
Проделана отличная работа, сверстано все верно согласно дизайну, весь функционал работает корректно, круто, что заиспользовала React.memo, propTypes описаны везде где требуются и практически без ошибок, но есть некоторые вещи, которые надо исправить для принятия работы:

- [x] Надо перевести все компонента на jsx все таки задание звучит как: “Проект. Написать весь JSX и сверстать”
- [ ] Надо исправить везде proptypes будь с ними повнимательнее, старайся избегать any
- [ ] Надо поправить нейминги, каждое название переменной должно ясно говорить нам, что лежит в ней
- [ ] Исправить некорректное использование async await операторов
- [x] Убрать retry запросов
- [ ] Вынести все расчеты и функции из верстки в компоненты
- [ ] Убрать все излишние действия 
- [x] Раз получилось все таки установить нужные зависимости, давай переделаем на CRA template typescipt
- [ ] К сожалению важно соблюдать ТЗ, так, что давай реализуем компонент modalOverley

2021-11-18 20:42 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.js
> +        props.burger.length > 1 &&<>
`надо исправить` надо показывать ингредиенты в конструкторе даже если он всего один, так, что по крайней мере >0 надо сделать, а еще лучше вот так `Boolean(props.burger.length)`

2021-11-18 20:42 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.js
> +            <BurgerElement  {...props.burger[0]}></BurgerElement>
`можно лучше` зачем тут деструктуризация, кажется можно без нее обойтись, а еще лучше там где получаешь пропсы в компонента добавь [деструктуризацию](https://ichi.pro/ru/unictoz-te-react-props-s-pomos-u-destrukturizacii-ob-ektov-es6-dla-bolee-cistogo-koda-63240260175949) , чтобы не обращаться постоянно через props и не мутировать случайно данные

2021-11-18 20:42 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.js
> +                {props.burger.filter(ingr=>ingr.type=='undefined').map((ingredient, index)=>
`надо исправить` кажется тут что то не так делаешь во первых нужно всегда избегать использования двойного равенства и сравнивать всегда без приведения типов при помощи `===` и кажется у ингредиентов в бургере тип должен быть всегда описан

2021-11-18 20:42 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.js
> +    <SubmitOrder  price={props.burger.map(ingr=>ingr.price).reduce((s,price)=>s+price)}/>
`надо исправить` лучше не делать никаких расчетов внутри верстки, они всегда должны быть внутри компонента, во первых так семантически более верно, во вторых расчеты в верстке всегда влекут за собой большое количество излишних перерисовок

2021-11-18 20:42 UTC, grishbar commented on src/components/burger-element/burger-element.js
> +export default React.memo(BurgerElement);
`отлично` классно, что знаешь такой хук и заиспользовала его

2021-11-18 20:42 UTC, grishbar commented on src/components/burger-ingredient-card/burger-ingredient-card.js
> +     <div className={styles.ingredient_card}  onClick={()=>{if(currentIngredientId)setCurrentIngredientId(null); else setCurrentIngredientId(props.ingredient._id)}}>
`надо исправить` эту функцию надо тоже вынести из onClick и описать ее в компоненте

2021-11-18 20:42 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.js
> +    },[props])
`надо исправить` это можно убрать можешь отрисовывать исходя из props.ingredients незачем переносить их в state

2021-11-18 20:42 UTC, grishbar commented on src/components/ingredient-details/ingredient-details.module.css
> +}
`надо исправить` классы должны нести осмыссленное название, что хранит тэг с твоим классом или за что он отвечает, но не стилевое значение

2021-11-18 20:42 UTC, grishbar commented on src/components/modal/modal.js
> +  },[]);
`отлично` хорошо, что не забыла удалить eventListener при размонтировании компонента

2021-11-18 20:42 UTC, grishbar commented on src/components/modal/modal.js
> +    }
`можно лучше` у конструкции switch case всегда должен быть обработан дефолтные случай

2021-11-18 20:42 UTC, grishbar commented on src/components/order-details/order-details.js
> +            <img src={DoneGif} className='pt-15 pb-15' alt='done'></img>
`надо исправить` alt картинки должен помогать тем кто плохо видит понять, что находится на этой картинке или какое ее функциональное назначение, слово done не дает нам ничего

2021-11-19 18:24 UTC, LarisaK12 commented on src/components/burger-constructor/burger-constructor.js
> +                {props.burger.filter(ingr=>ingr.type=='undefined').map((ingredient, index)=>
тип там либо 'top' либо 'bottom', либо 'undefined'. 'undefined' - это ингредиенты, которые надо показывать в середине, поэтому такой фильтр. почему использовала ==, так не понятно что это за 'undefined' - это неопределенная переменная или строка такая ). Но будем думать, что строка, поэтому сделаем ===

2021-11-21 03:33 UTC, grishbar approved these changes
Отлично! 👍  Вижу, что проведена большая работа по рефакторингу, все ошибки исправлены, теперь это отличное рабочее решение, если настроишь eslint и причешешь весь проект, то полчится прям готовое продакшн решение, а так все уже прекрасно, работу засчитываю, удачи в дальнейшем обучении)

2021-11-21 03:33 UTC, grishbar commented on src/components/app-header/app-header.jsx
> +export default AppHeader
`можно лучше` в принципе это вполне читаемо, но, чтобы сделать прям красиво и исправить все стилистические недочеты, то можешь установить и настроить eslint для этого запусти вот эту команду 
`npm i eslint-config-airbnb eslint-plugin-jsx-a11y --save-dev`
далее надо создать файлик `.eslintrc` в корне проекта куда надо записать:
```
{
    "extends": [
      "react-app",
      "airbnb",
      "plugin:jsx-a11y/recommended"
    ],
    "plugins": [
      "jsx-a11y"
    ],
    "rules": {
      "semi": 0,
      "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx", "tsx"] }]
    }
}
```
после этих действий у тебя в коде будет везде подсвечиваться некорректный синтаксис, сможешь исправить все ошибки и получится великолепный чистый код

2021-11-21 03:33 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    //const [ingredients,setIngredients] =React.useState([]);
`можно лучше` комментарии которые не документируют дальнейший код (не говорят, что будет происходит в последующих строчках под ними) должны быть удалены

2021-11-21 15:32 UTC, merged